# Site settings
title: Louis Rassaby
description: |
  Louis Rassaby is a Brooklyn-based software engineer and entrepreneur specializing in Scala and back-end development.
  He's the founder of Wirefreight and the Postpartum Project. Previously, Louis led the new products engineering team
  at Phosphorus Genomics.

url: http://rassaby.com

about_title: About
projects_title: Projects

# User settings
user_description_appendix: |
  I created this site to write about my interests: startups and entrepreneurship, design, data-intensive applications,
  functional programming, AR/VR, and machine learning. Above all, I love using computers to solve big problems.

  I built this site in [Jekyll][jekyll], and it's hosted for free on [GitHub Pages][gh-pages]. It's open source, so if
  you like it, feel free to fork it on [GitHub][github] and make your own version.

  [github]: https://github.com/lrassaby/lrassaby.github.io
  [gh-pages]: https://pages.github.com/
  [jekyll]: https://jekyllrb.com


email: louis@rassaby.com
linkedin: lrassaby
github: lrassaby
angellist: rassaby

relevant_tags: ['tech', 'design', 'music']

resume_url: https://docs.google.com/document/d/1dJIboSF-ktdaP28DDu-gcuOW1SCCnkSdqtodJGwYkaA/export?format=pdf

author: Louis Rassaby
author_title: Software Engineer
author_photo: profile-photo.jpg
user_description_short: |
  I'm a Brooklyn-based software engineer and entrepreneur. I'm the founder of [Wirefreight][wirefreight], a customer-service SaaS platform for logistics. I
  also co-founded the [Postpartum Project][ppp], a resource network for new mothers. Previously, I led the new products
  engineering team at Phosphorus Genomics, analyzing genetic data and educating tens of thousands of people on their risks of
  developing or passing on genetic diseases.

  Away from the keyboard, I make food and music. I'm half of a band called [Cellolele][cellolele] and I once played in
  an ad for [Versace][versace].

  [scala]: https://www.scala-lang.org/
  [cellolele]: /cellolele-toxic/
  [wirefreight]: http://wirefreight.com/
  [ppp]: http://postpartumproject.com/
  [versace]: /versace-eyewear


## Disqus
disqus_identifier: rassaby

## Tracker
google_analytics_id: UA-109461282-1

keywords: 'software,engineer,design,scala,cello,music,louis rassaby'

## URLs
permalink: ':title/'

baseurl: ''
projects_url: '/'
about_url: '/about'


include: [_pages]
exclude: ['package.json', 'src' , 'node_modules', 'Gemfile', 'LICENSE', 'gulpfile.js', 'README.md']